source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end

target 'CenariusExample' do
  pod 'Cenarius', :path => '..'
end

